const CHANGE_INPUT_VALUE = 'CHANGE_INPUT_VALUE'
const CHANGE_OUTPUT_VALUE = 'CHANGE_OUTPUT_VALUE'
const CONVERT_INPUT_VALUE = 'CONVERT_INPUT_VALUE'

export { CHANGE_INPUT_VALUE, CHANGE_OUTPUT_VALUE, CONVERT_INPUT_VALUE }
