export const actionTypes = {
  SET_INPUT_VALUE: 'SET_INPUT_VALUE',
  SET_OUTPUT_VALUE: 'SET_OUTPUT_VALUE',
  CONVERT_INPUT_VALUE: 'CONVERT_INPUT_VALUE',
  RESET_OPTIONS: 'RESET_OPTIONS',
  SET_PREFIX_OPTION: 'SET_PREFIX_OPTION'
}
