const SET_INPUT_VALUE = 'SET_INPUT_VALUE'
const SET_OUTPUT_VALUE = 'SET_OUTPUT_VALUE'
const CONVERT_INPUT_VALUE = 'CONVERT_INPUT_VALUE'

const RESET_OPTIONS = 'RESET_OPTIONS'
const SET_PREFIX_OPTION = 'SET_PREFIX_OPTION'

export { SET_INPUT_VALUE, SET_OUTPUT_VALUE, CONVERT_INPUT_VALUE, SET_PREFIX_OPTION, RESET_OPTIONS }
